### ISSUE TITLE
Jetty webSocket Timeout on Read Error

### ISSUE THREAD

**Issue by zhang1g2** [guooscar/JazminServer#20]
**there is a error while using JazminDeployer , the error log is like :**
[2016-09-11 16:21:03,719] [INFO ] [WebRequestLog] [WorkerThread-28 - /deployer/HEARTBEAT/?v-uiId=0]- [0:0:0:0:0:0:0:1:58629] HTTP/1.1 [POST]  0 
九月 11, 2016 4:21:29 下午 org.atmosphere.container.Jetty9WebSocketHandler onWebSocketError
严重: {}
java.net.SocketTimeoutException: Timeout on Read
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:526)
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:173)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:496)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback$1.run(AbstractConnection.java:582)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by guooscar** [comment]
it's not an error it's just warning message

**Comment by mudlee** [comment]
Can it be avoided somehow?
